config/routes.rb
Quesos::Application.routes.draw do

  resources :events do
    collection do
      get 'filter'
      post 'export'
    end
  end
  
  resources :events
  
  resources :productos

  resources :reservas

  resources :dispatches

  get "receive/update"

  resources :orders

  get "bodega/index"
  get "mailer/readInbox"
  get "stock/show"
  get "order/run_process"

  match "/order/run_process" => "orders#run_process"
  match "/bodegas" => "bodega#index"
  match "/stock/:sku" => "stock#show"
  match "/event/filter" => "events#filter"

  root :to => "dispatches#index"

end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  attr_accessible :qty, :sku

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |reserva|
        csv << reserva.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  require 'will_paginate'

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.paginate(:page => params[:page], :per_page => 10)
    @reservas_all = Reserva.paginate(:page => params[:page], :per_page => 100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservas }
      format.csv { send_data @reserva_all.to_csv }
      format.xls # { send_data @reserva.to_csv(col_sep: "\t") }
    end
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/new
  # GET /reservas/new.json
  def new
    @reserva = Reserva.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/1/edit
  def edit
    @reserva = Reserva.find(params[:id])
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(params[:reserva])

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render json: @reserva, status: :created, location: @reserva }
      else
        format.html { render action: "new" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservas/1
  # PUT /reservas/1.json
  def update
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      if @reserva.update_attributes(params[:reserva])
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva = Reserva.find(params[:id])
    @reserva.destroy

    respond_to do |format|
      format.html { redirect_to reservas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_form.html.erb
<%= form_for @reserva, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :sku, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sku, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qty, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :qty, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reservas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservas/index.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_reserva_path,
            :class => 'btn btn-primary' %>
    <!--<%= link_to('CSV', reservas_path(format: "csv"), :class => 'btn btn-info')  %>-->
    <%= link_to('Excel', reservas_path(format: "xls"), :class => 'btn btn-success')  %>
  </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sku) %></th>
      <th><%= model_class.human_attribute_name(:qty) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= link_to reserva.id, reserva_path(reserva) %></td>
        <td><%= reserva.sku %></td>
        <td><%= reserva.qty %></td>
        <td><%=l reserva.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reserva_path(reserva), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reserva_path(reserva),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
     <div class="container">
      <div class="row">
        <div class="span1"></div>
        <div class="span7">

          <div class="flickr_pagination"><%= will_paginate @reservas, :container => false %> 
          </div>

        </div>
        <div class="span1"></div>
      </div>
    </div>
  </tbody>
</table>

app/views/reservas/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">SKU</Data></Cell>
        <Cell><Data ss:Type="String">Cantidad</Data></Cell>
      </Row>
    <% Reserva.all.each do |reserva| %>
      <Row>
        <Cell><Data ss:Type="String"><%= reserva.sku %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= reserva.qty %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/reservas/new.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservas/show.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:sku) %>:</strong></dt>
  <dd><%= @reserva.sku %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty) %>:</strong></dt>
  <dd><%= @reserva.qty %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reservas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reserva_path(@reserva), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reserva_path(@reserva),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>