config/routes.rb
Quesos::Application.routes.draw do

  resources :events do
    collection do
      get 'filter'
      post 'export'
    end
  end
  
  resources :events
  
  resources :productos

  resources :reservas

  resources :dispatches

  get "receive/update"

  resources :orders

  get "bodega/index"
  get "mailer/readInbox"
  get "stock/show"
  get "order/run_process"

  match "/order/run_process" => "orders#run_process"
  match "/bodegas" => "bodega#index"
  match "/stock/:sku" => "stock#show"
  match "/event/filter" => "events#filter"

  root :to => "dispatches#index"

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps::Created

#Ejemplo de registro de eventos:
#Event.create(type: "recibido", qty: 1, unit: "UN", rut: "1233-2", orderId: 1232445, sku: "2343455")



  field :type, type: String
  field :qty, type: BigDecimal
  field :unit, type: String
  field :rut, type: String
  field :orderId, type: Integer
  field :sku, type: String
  validates :type, :presence => true
  validates :rut, :presence => true
  validates :orderId, :presence => true
  validates :sku, :presence => true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << fields.collect { |field| field[0] }
      all.each do |event|
        csv << event.attributes.values_at(*fields.collect { |field| field[0] })
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order_by([[:created_at, :desc]]).limit(10)
    @tipos=[""]
    @tipos=(@tipos<<Event.all.distinct(:type)).flatten
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events}
      format.xls 
    end
  end

  def export
    if params[:type]=="" or params[:type]==nil
      @events = Event.where(:created_at.gte => params[:from]).and(:created_at.lte => params[:to]).order_by([[:created_at, :desc]])
    else
      @events = Event.where(:created_at.gte => params[:from]).and(:created_at.lte => params[:to]).and(type: params[:type]).order_by([[:created_at, :desc]])
    end
    @filtered=@events
    respond_to do |format|
      format.json { render json: @events }
      format.csv { send_data @events.to_csv }
      format.xls 
    end
  end
  def filter
    fromHash=params[:from]
    toHash=params[:to]
    
    @from=Time.new(fromHash[:year],fromHash[:month], fromHash[:day], fromHash[:hour], fromHash[:minute])
    @to=Time.new(toHash[:year],toHash[:month], toHash[:day], toHash[:hour], toHash[:minute])
    
    if params[:type]=="" or params[:type]==nil
    
    @events = Event.where(:created_at.gte => @from).and(:created_at.lte => @to).order_by([[:created_at, :desc]])
    else
    @events = Event.where(:created_at.gte => @from).and(:created_at.lte => @to).and(type: params[:type]).order_by([[:created_at, :desc]])
    end

    @filtered=@events
    @tipos=[""]
    @tipos=(@tipos<<Event.all.distinct(:type)).flatten
    respond_to do |format|
      format.html # filter.html.erb
      format.json { render json: @events }
      format.csv { send_data @events.to_csv }
      format.xls 
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :qty %><br />
    <%= f.text_field :qty %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :rut %><br />
    <%= f.text_field :rut %>
  </div>
  <div class="field">
    <%= f.label :orderId %><br />
    <%= f.number_field :orderId %>
  </div>
  <div class="field">
    <%= f.label :sku %><br />
    <%= f.text_field :sku %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Time Stamp</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Qty</Data></Cell>
        <Cell><Data ss:Type="String">Unit</Data></Cell>
        <Cell><Data ss:Type="String">Rut</Data></Cell>
        <Cell><Data ss:Type="String">OrderId</Data></Cell>
        <Cell><Data ss:Type="String">SKU</Data></Cell>
      </Row>
    <% @filtered.each do |event| %>
      <Row>
        <Cell><Data ss:Type="String"><%= event.created_at.strftime("%Y-%m-%d %H:%M:%S")%></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.type %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= event.qty %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.unit %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.rut %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.orderId %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.sku %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/events/filter.html.erb
<div class="page-header">

<div class="span3"><h1>Log Filtrado</h1></div>
  <div class="span1">
<%= form_tag("/events/export.xls", :method => "post") do %>
<%= hidden_field_tag(:from, @from) %>
<%= hidden_field_tag(:to, @to) %>
<%= hidden_field_tag(:type, @eventType) %>
<%= submit_tag("Excel", :class => 'btn btn-success') %>
<% end %></div>
</div>
  <table class="table table-striped">
  <tr>
    <thead>
      <th>Tipo</th>
      <th>Timestamp</th>
      <th>Cantidad</th>
      <th>Unidad</th>
      <th>Rut</th>
      <th>OrderID</th>
      <th>Sku</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
  </tr>
<% @events.each do |event| %>
  <tr>
    <td><%= event.type %></td>
    <td><%= event.created_at.in_time_zone %></td>
    <td><%= event.qty %></td>
    <td><%= event.unit %></td>
    <td><%= event.rut %></td>
    <td><%= link_to event.orderId , order_path(event.orderId)%></td>
    <td><%= event.sku %></td>
  </tr>
<% end %>
</table>
<br>
<br><h4>Seleccione un rango de tiempo y tipo de evento</h4>
<%= form_tag("/events/filter", :method => "get") do %>
  <div class="field">
  <%= label_tag(:from, "Desde:") %>
  <%= select_datetime(nil, :prefix => 'from') %>
  </div>
  <div class="field">
  <%= label_tag(:to, "Hasta:") %>
  <%= select_datetime(Time.now, :prefix => 'to') %>
  </div>
  <div class="field">
  <%= label_tag(:type, "Tipo:") %>
  <%= select_tag(:type, options_for_select(@tipos) ) %>
  </div>
  <%= submit_tag("Filtrar") %>
<% end %>

<br />

app/views/events/index.html.erb
<h1>Log de Eventos</h1>

<table class="table table-striped">
  <tr>
  <thead>
    <th>Tipo</th>
    <th>Timestamp</th>
    <th>Cantidad</th>
    <th>Unidad</th>
    <th>Rut</th>
    <th>OrderID</th>
    <th>Sku</th>
  </thead>

  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.type %></td>
    <td><%= event.created_at %></td>
    <td><%= event.qty %></td>
    <td><%= event.unit %></td>
    <td><%= event.rut %></td>
    <td><%= link_to event.orderId , order_path(event.orderId)%></td>
    <td><%= event.sku %></td>
  </tr>
<% end %>
</table>

<p>* Se muestran los últimos 10 eventos</p>
<br><h4>Seleccione un rango de tiempo y tipo de evento</h4>
<%= form_tag("/event/filter", :method => "get") do %>
  <div class="field">
  <%= label_tag(:from, "Desde:") %>
  <%= select_datetime(nil, :prefix => 'from') %>
  </div>
  <div class="field">
  <%= label_tag(:to, "Hasta:") %>
  <%= select_datetime(Time.now, :prefix => 'to') %>
  </div>
  <div class="field">
  <%= label_tag(:type, "Tipo:") %>
  <%= select_tag(:type, options_for_select(@tipos) ) %>
  </div>
  <%= submit_tag("Filtrar") %>
<% end %>

app/views/events/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Time Stamp</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Qty</Data></Cell>
        <Cell><Data ss:Type="String">Unit</Data></Cell>
        <Cell><Data ss:Type="String">Rut</Data></Cell>
        <Cell><Data ss:Type="String">OrderId</Data></Cell>
        <Cell><Data ss:Type="String">SKU</Data></Cell>
      </Row>
    <% @filtered.each do |event| %>
      <Row>
        <Cell><Data ss:Type="String"><%= event.created_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.type %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= event.qty %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.unit %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.rut %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.orderId %><</Data></Cell>
        <Cell><Data ss:Type="String"><%= event.sku %><</Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @event.type %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @event.created_at %>
</p>

<p>
  <b>Qty:</b>
  <%= @event.qty %>
</p>

<p>
  <b>Unit:</b>
  <%= @event.unit %>
</p>

<p>
  <b>Rut:</b>
  <%= @event.rut %>
</p>

<p>
  <b>Orderid:</b>
  <%= @event.orderId %>
</p>

<p>
  <b>Sku:</b>
  <%= @event.sku %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>