config/routes.rb
Quesos::Application.routes.draw do

  resources :events do
    collection do
      get 'filter'
      post 'export'
    end
  end
  
  resources :events
  
  resources :productos

  resources :reservas

  resources :dispatches

  get "receive/update"

  resources :orders

  get "bodega/index"
  get "mailer/readInbox"
  get "stock/show"
  get "order/run_process"

  match "/order/run_process" => "orders#run_process"
  match "/bodegas" => "bodega#index"
  match "/stock/:sku" => "stock#show"
  match "/event/filter" => "events#filter"

  root :to => "dispatches#index"

end

app/models/producto.rb
class Producto < ActiveRecord::Base

  attr_accessible :descripcion, :desde, :hasta, :precio, :sku

  scope :activo, lambda {where("hasta > ? and Desde < ?",Date.today,Date.today)}

  def self.active
    Producto.find(:all, :conditions => ["hasta > ? and desde < ?", Date.today, Date.today])
  end

  def self.by_sku(sku)
    Producto.find(:all, :conditions => ["hasta > ? and desde < ? and sku = ?", Date.today, Date.today, sku]).last
  end



end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  require 'will_paginate'

  # GET /productos
  # GET /productos.json
  def index
    #activos = Producto.active
    #@productos = activos.paginate(:page => params[:page], :per_page => 10)
    @productos = Producto.activo.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for @producto, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :sku, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :sku, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :precio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :precio, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desde, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :desde, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hasta, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :hasta, :class => 'date_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                productos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/index.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sku) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:precio) %></th>
      <th><%= model_class.human_attribute_name(:desde) %></th>
      <th><%= model_class.human_attribute_name(:hasta) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= link_to producto.id, producto_path(producto) %></td>
        <td><%= producto.sku %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.desde %></td>
        <td><%= producto.hasta %></td>
        <td><%=l producto.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_producto_path(producto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      producto_path(producto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_producto_path,
            :class => 'btn btn-primary' %>

app/views/productos/new.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/show.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:sku) %>:</strong></dt>
  <dd><%= @producto.sku %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @producto.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio) %>:</strong></dt>
  <dd><%= @producto.precio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desde) %>:</strong></dt>
  <dd><%= @producto.desde %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hasta) %>:</strong></dt>
  <dd><%= @producto.hasta %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              productos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_producto_path(@producto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              producto_path(@producto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>