config/routes.rb
Quesos::Application.routes.draw do

  resources :events do
    collection do
      get 'filter'
      post 'export'
    end
  end
  
  resources :events
  
  resources :productos

  resources :reservas

  resources :dispatches

  get "receive/update"

  resources :orders

  get "bodega/index"
  get "mailer/readInbox"
  get "stock/show"
  get "order/run_process"

  match "/order/run_process" => "orders#run_process"
  match "/bodegas" => "bodega#index"
  match "/stock/:sku" => "stock#show"
  match "/event/filter" => "events#filter"

  root :to => "dispatches#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quesos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'gmaps4rails/gmaps4rails.base.js' %>
  <%= javascript_include_tag 'gmaps4rails/gmaps4rails.bing.js' %>
  <%= javascript_include_tag 'gmaps4rails/gmaps4rails.googlemaps.js' %>
  <%= javascript_include_tag 'gmaps4rails/gmaps4rails.mapquest.js' %>
  <%= javascript_include_tag 'gmaps4rails/gmaps4rails.openlayers.js' %>
  <%= javascript_include_tag "jquery-1.10.1.min", "highcharts", "exporting" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand">Quesos Hualpen</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Inicio", root_path%></li>
            <li><%= link_to "Ordenes", orders_path %></li>
            <li><%= link_to "Reservas", reservas_path %></li>
            <li><%= link_to "Despachos", dispatches_path %></li>
            <li><%= link_to "Productos", productos_path %></li>
            <li><%= link_to "Data Warehouse", events_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9">
        <%= yield %>
        <%= yield :scripts %>
      </div>
      <div class="span3">
        <h2>Twitter</h2>
        <a class="twitter-timeline" href="https://twitter.com/QuesosHualpen4" data-widget-id="342634870478082048">Tweets por @QuesosHualpen4</a>
        <script>
          !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        </script>
      </div>
    </div>
  </div>
</body>
</html>